### ISSUE TITLE
Custom operator : a non commutative variant of combineWith 

### ISSUE THREAD

**Issue by doofin** [raquo/Airstream#35]
Hi I am trying to implement a custom operator that has the same type as combineWith but with different semantics.It emits only when the first stream emits ,combining with the latest element of the second stream.This can be think of as  an non commutative version of current combineWith.However the required modification  seems not obvious :
```scala
/** Stream that combines the latest values from two streams into a tuple.
  * Only fires after both streams have sent a value.
  *
  * Note: this stream forgets any previous values of parent streams once it's stopped
  *
  * @param combinator Note: Must not throw. Must have no side effects. Can be executed more than once per transaction.
  */
class CombineEventStream2[A, B, O](
  parent1: EventStream[A],
  parent2: EventStream[B],
  combinator: (Try[A], Try[B]) => Try[O]
) extends EventStream[O] with CombineObservable[O] {

  override protected[airstream] val topoRank: Int = (parent1.topoRank max parent2.topoRank) + 1

  private[this] var maybeLastParent1Value: Option[Try[A]] = None
  private[this] var maybeLastParent2Value: Option[Try[B]] = None

  parentObservers.push(
    InternalParentObserver.fromTry[A](parent1, (nextParent1Value, transaction) => {
      // println(s"> updated p1 value to $nextParent1Value")
      maybeLastParent1Value = Some(nextParent1Value)
      maybeLastParent2Value.foreach { lastParent2Value =>
        internalObserver.onTry(combinator(nextParent1Value, lastParent2Value), transaction)
      }
    }),
    InternalParentObserver.fromTry[B](parent2, (nextParent2Value, transaction) => {
      // println(s"> updated p1 value to $nextParent1Value")
      maybeLastParent2Value = Some(nextParent2Value)
      maybeLastParent1Value.foreach { lastParent1Value =>
        internalObserver.onTry(combinator(lastParent1Value, nextParent2Value), transaction)
      }
    })
  )

  override protected[this] def onStop(): Unit = {
    maybeLastParent1Value = None
    maybeLastParent2Value = None
    super.onStop()
  }

}
```

**Comment by raquo** [comment]
You can use `stream1.withCurrentValueOf(stream2.toWeakSignal).collect { case (a, Some(b)) => (a, b) } ` for this. The `collect` part is optional, I assume that's what you want.

**Comment by doofin** [comment]
@raquo Thanks! That works. Would you mind me to create a new operator(maybe called combineA?) for this specifically? I find it useful in 2 scenarios during my application.

**Comment by raquo** [comment]
I don't know, I'm not sure if we should do this. Often times when people want to look at the "last emitted event", what they actually need is a Signal rather than an EventStream, so facilitating such access might not be a good idea.

We could implement a `withLatestEventFrom(eventStream)` as an addition to `withCurrentValueOf(signal)`, but if it's part of the library, the implementation would need to be different than the one liner I provided here, specifically we should not be converting stream to signal as that has potential performance implications (`==` comparison) that would not be apparent from the method signature that has nothing to do with signals.

You should use this one liner for now, I'll think about it...
