### ISSUE TITLE
Add method variant of EvenStream.merge?

### ISSUE THREAD

**Issue by shado23** [raquo/Airstream#97]
Maybe that's just me, but it took me quite a while to discover its existence, as I was expecting there to be some kind of 'concat' or 'merge' method on EventStream (maybe even a '++' alias).

Is there a reason why this doesn't exist?

**Comment by raquo** [comment]
Hey, sorry, somehow I missed this issue's notification! Getting back to working on 15.0.0 now, and just saw it.

Yep I can add a `mergeWith` operator on streams, not sure why I didn't do that from the start tbh.

Re: naming – `concat` is typically associated with [different semantics](https://reactivex.io/documentation/operators/concat.html) in observables so I can't use that for merging. Kinda same for `++` since it's usually associated with `concat`, plus I'm not a fan for symbolic names in observables – there's just too many ways to combine two streams for `++` to have an _obvious_ meaning (the same is not true for e.g. the collections library because it does not deal with time).

**Comment by shado23** [comment]
No worries.

Having a `mergeWith` method sounds good to me. It seems it's called `merge` in Monix Observable, fs2, and ZIO streams (although I didn't check whether the semantics match exactly), but you may have reasons to diverge.

**Comment by raquo** [comment]
I'm following the naming of our `combineWith` for consistency. That one just happens to be historical already, I don't think one or the other name is fundamentally better, just don't want to make our big video out of date (text is easy to update, video – not so much). IDE's autocomplete should expose both names equally well anyway.

**Comment by shado23** [comment]
Fair enough.

**Comment by raquo** [comment]
Makes sense, I'll add that method. Not sure why I didn't do that to start
with tbh.

> Message ID: ***@***.***>
>
--Nikita
